module SpreeGoogleProducts
  module Generators
    class UninstallGenerator < Rails::Generators::Base
      
      def drop_tables
        return unless yes?("WARNING: This will destroy all Google Shopping data (Credentials, Product Settings, Taxonomies). Are you sure? [y/N]")

        # We use the Rake task to ensure the DB connection is established correctly 
        # in all environments (Docker, Codespaces, etc.)
        run 'bundle exec rake spree_google_shopping:cleanup'
      end

      def remove_migrations
        # Find migration files generated by this gem
        migration_files = Dir.glob("db/migrate/*add_spree_google_shopping_tables.spree_google_products.rb")
        # Fallback for older installs
        migration_files += Dir.glob("db/migrate/*spree_google_products.rb")

        if migration_files.any?
          migration_files.uniq.each do |file|
            # 1. Clean Database History (CRITICAL for re-installation support)
            version = File.basename(file).split('_').first
            if version.match?(/^\d+$/)
              # Use rails runner to delete the schema migration record safely
              # Escaping quotes is necessary for the runner command
              run "bin/rails runner \"ActiveRecord::Base.connection.execute(\\\"DELETE FROM schema_migrations WHERE version = '#{version}'\\\")\""
              puts "🧹 Removed version #{version} from schema_migrations."
            end

            # 2. Delete the file
            remove_file file
          end
          puts "🗑️  Removed migration files."
        else
          puts "⚠️  No specific migration files found to remove."
        end
      end

      def remove_initializer
        remove_file "config/initializers/force_encryption_keys.rb"
      end

      def clean_env_reminder
        puts "\n"
        puts "⚠️  IMPORTANT: We did not remove the Encryption Keys from your .env file."
        puts "   If you are not using them for other plugins, please manually remove:"
        puts "   - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY"
        puts "   - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY"
        puts "   - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT"
        puts "\n"
        puts "✅ Spree Google Products has been uninstalled."
      end
    end
  end
end
